### ISSUE TITLE
Missing Header File SESepsis.h

### ISSUE THREAD

**Issue by ahamdy47** [BioGearsEngine/core#11]
Hey keepers of BioGearsEngine repo, I am still brand new to this environment but I am trying to run the core build in a docker container and ran across a compilation issue, the compiler failed on this particular file `projects/howto/SepsisDynamic/src/HowTo-SepsisDynamic.cpp`  I did a a little digging and noticed this corresponding line `#include <biogears/cdm/patient/actions/SESepsis.h>` is looking for the header file that has been deleted in the latest commit (about 7 days ago of this post) but this file has not been updated. Can someone please get back to me whether a fix needs to happen in this repo, or just modify it locally?
Regards, Ahmed.

**Comment by mcmcdaniel** [comment]
Hi Ahmed,

Thanks for reaching out.  We've been making some changes to our core repo re: sepsis that were not brought over to the development kit.  I'll update HowTo-SepsisDynamic today and push it up today.

**Comment by ajbaird** [comment]
Thanks mcmcdaniel! if you push that up as a quick patch we can merge it in today. ahamdy, let me know if that works for your build step once it gets merged.

**Comment by ajbaird** [comment]
Sepsis how-to has been updated, tested and working. If something else pops up let us know. Thanks for the heads up!

**Comment by ahamdy47** [comment]
Thank you guys!
