### ISSUE TITLE
Speed compare to 6.3.0

### ISSUE THREAD

**Issue by jeldalam** [BioGearsEngine/core#12]
Hi BioGearsEngine team,

This is more a question rather than an issue.

First, I was able to build and using BioGearsEngine 7.2.1, thanks for the help of @StevenAWhite 
But I found out the engine now run a lot slower than 6.3.0

This is extracted from the log:
```
[0(s)] Executing Scenario
[60(s)] Current Time is 60s, it took 152.943s to simulate the past 60s
```

Is this normal and expected? I'm using Macbook Pro 2019 (2.3GHz 8-core Intel Core i9, 16GB 2400MHz DDR4)
I was using the engine to simulate realtime event, because in 6.3.0, it very fast and just took about 1s to simulate 5s on my Mac.

What can I do to make the engine consume more CPUs/resources of my machine so it can run faster, and is it possible?

Second, what is the version you guys use to output the showcase chart of Multi-Trauma on home page (https://biogearsengine.com/)? I'm using 7.2.1 and run the showcase in core/share/Scenarios/Showcase/CombatMultitrauma.xml and the output is very different.

Thanks.

**Comment by StevenAWhite** [comment]
That run-time ratio is very unusual. It normally takes about 1s to simulate 5-8 depending on the machine.  I would assume the build options have something to do with the performance loss.  Double check that your CMAKE_BUILD_TYPE is set to release. I'll run some speed test against our build machine builds on Tuesday and can give you some better estimates on performance.

**Comment by StevenAWhite** [comment]
[AsthmaAttack.log](https://github.com/BioGearsEngine/core/files/3913069/AsthmaAttack.log)

I'm attaching a log of a scenario running from a release build on the following machine.

Hardware Overview:

  Model Name:	Mac mini
  Model Identifier:	Macmini7,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

**Comment by StevenAWhite** [comment]
```
2019-12-02 14:40:14,505 [INFO]  : [663.06(s)] Inhaler actuated!
2019-12-02 14:40:14,505 [INFO]  : [663.06(s)] Airway Mode : Inhaler
2019-12-02 14:40:14,975 [INFO]  : [664.64(s)] [Event] 664.64(s),  Patient no longer has Tachypnea
2019-12-02 14:40:15,663 [INFO]  : [668.08(s)] Completed Conscious Respiration Command : Forced Inhale
	InspiratoryCapacityFraction: 1
	Period: 5(s)
2019-12-02 14:40:17,686 [INFO]  : [678.1(s)] Completed Conscious Respiration Command : Breath Hold
	Period: 10(s)
2019-12-02 14:40:18,288 [INFO]  : [681.1(s)] Completed Conscious Respiration Command : Forced Exhale
	ExpiratoryReserveVolumeFraction: 0
	Period: 3(s)
2019-12-02 14:40:18,295 [INFO]  : [681.12(s)] [Event] 681.12(s),  Patient has Bradypnea
2019-12-02 14:40:18,688 [INFO]  : [683.06(s)] [Event] 683.06(s),  Patient no longer has Bradypnea
2019-12-02 14:40:18,688 [INFO]  : [683.06(s)] [Event] 683.06(s),  Patient has Tachypnea
2019-12-02 14:40:28,299 [INFO]  : [720(s)] Current Time is 720s, it took 14.388s to simulate the past 60s
2019-12-02 14:40:40,385 [INFO]  : [780(s)] Current Time is 780s, it took 12.085s to simulate the past 60s
2019-12-02 14:40:52,678 [INFO]  : [840(s)] Current Time is 840s, it took 12.293s to simulate the past 60s
2019-12-02 14:41:04,973 [INFO]  : [900(s)] Current Time is 900s, it took 12.294s to simulate the past 60s
2019-12-02 14:41:17,177 [INFO]  : [960(s)] Current Time is 960s, it took 12.203s to simulate the past 60s
2019-12-02 14:41:17,190 [INFO]  : [960.06(s)] [Action] 960.06(s), Patient Action : Assessment Request
	Comment: Assessment: Pulmonary function test
	Type: PulmonaryFunctionTest
```

So for this machine your looking at about 5:1  I would expect yoru i9 to see a pretty noticible performance mark.  Couple of things to note. BioGears is single threaded per simulation. This is designed to allow you to run multiple simulations in parallel or to split computer resources with other process your integrating the library in to. So your per core FLOP rate is your best indicator of improvement between processors. 

So, our last release 7.2.1 defaulted to Debug unless you passed `CMAKE_BUILD_TYPE=Release`.  Master and all future releases default to Release, which is likely to be the most often compiled build variant.  If you are building in release and it is still running that slow. We likely want to look at your Eigen version or possibly your disk IO to determine where the bottle neck is.

**Comment by StevenAWhite** [comment]
>Second, what is the version you guys use to output the showcase chart of Multi-Trauma on home page (https://biogearsengine.com/)? I'm using 7.2.1 and run the showcase in core/share/Scenarios/Showcase/CombatMultitrauma.xml and the output is very different.

So, the playback on the website is probably based on 6.3.0. The dataset also goes through post processing to smooth out the code and reduce the data density. This is mostly to improve performance of playback in the javascript tools.  We are in the process of prepping the next release and will try to upload current versions of the data set when it hits gold.

**Comment by jeldalam** [comment]
Hi @StevenAWhite,

Thanks for the info, I'll try to build with release flag to see if it help. Even though, I was using 6.3.0 to run the predefined CombatMultitrauma and still not get the same result as the chart on the home page's show case. Are you sure it's 6.3.0? Because we have a doctor state that the chart on home page is more correct so I want to try to get the same result of it.

Thanks again.

**Comment by jeldalam** [comment]
Hi,

I was successully build with release flag, it's true that the speed is due to debug build, thanks again.
Here is the result, still on the same spec

```
[0(s)] Executing Scenario
[60(s)] Current Time is 60s, it took 9.776s to simulate the past 60s
```

And to more specific about the showcase question, can you tell me how can you guys achieve the drop noted in the Soldier Multi-Trauma chart below (showcase on biogears homepage), is that really from old version? It might be not from 6.3, If so, how can we achieve that in current version?

![Screen Shot 2019-12-25 at 3 58 30 PM](https://user-images.githubusercontent.com/14287641/71440424-a4cbfe80-272f-11ea-9f71-753d0ab6aaa3.png)

**Comment by mcmcdaniel** [comment]
The timeline for the Combat Multitrauma scenario (located below the scenario player) shows that a bolus of morphine is given at 9:30.  Morphine exerts some respiratory depressive effects in addition to its analgesic action, which is why the oxygen saturation falls.  We have updated our pharmacodynamic model to account for the fact that morphine generally exhibits a lag in effect onset time (see, for instance:  Lötsch, J. (2005). Pharmacokinetic–pharmacodynamic modeling of opioids. Journal of pain and symptom management, 29(5), 90-103).  Thus, running the scenario out for a longer period of time should yield similar results.  You could also vary the size of the morphine bolus or use a faster-onset opioid, like fentanyl.
