### ISSUE TITLE
7.3 Basic installation and running biogears

### ISSUE THREAD

**Issue by ahamdy47** [BioGearsEngine/core#13]
Hi maintainers of Biogears, I am having an issue getting the cmd_bio binary running properly I am using Ubuntu 18.04 X86_64, and I think I have it installed correctly by following the wiki and then running "ninja install" in biogears core/build (missing in the wiki, only states "ninja scenario_driver"). My question is how do I use biogears as standalone and with AMM. I have got the environment where running "cmd_bio THREADS 1 GENDATA GENSTATES" generates a bunch of .xml file under various directory like "nutrition" and "substance" followed by "done!". Where do I view this files and how do I know if I am using Biogears correctly? 
p.s. I installed all the build int "/usr"
regards AHamdy
Edit: I am using 7.2.1

**Comment by StevenAWhite** [comment]
So, it sounds like you are using cmd_bio correctly.

The GENSTATES and GENDATA targets are designed to rebuild a series of XML filles which BioGears needs to run from the source data provided in the build.  Normally, they only need to be run after you make changes to the CDM when developing for BioGears, 

I think your next test should be to run a BioGears scenario from the runtime directory of the build tree.     assuming your in runtime something like ../../outputs/bin/scenario_driver Showcase/AsthmaAttack  should start running a biogears scenario and produce a AsthmaAttack.csv and AsthmaAttack.log file for review.  For legacy purposes I believe scenario_driver auto appends Scenarios/ to the given input so you only have to hand it relative paths of the Scenario directory in run time. Hopefully this helps you get started, but I can provide more detailed documentation tomorrow.  

As a side note I'm not sure if putting biogears in /usr is the best idea.   All of the BioGears executables and runtimes require a pretty dense directory structure to read runtime data from.  While you could put biogears library and binary outputs, you probobly want your runtime dir to be placed in your homedir or /opt/biogears.   This will just help all your system libraries and executables stay clean.

**Comment by ahamdy47** [comment]
Hey Steven thank you for the quick response I seem to be on the right path except when I ran $ scenario driver AsthmaAttack.xml it printed out a few errors, now I found the Scenarios directory under the build environment "biogears/core/share/Scenarios/Showcase" but not in the output folder "/usr/share/" below is an attached image.
Thanks again, AHamdy!
![Screenshot from 2020-01-10 09-26-42](https://user-images.githubusercontent.com/25650280/72160727-cf06f880-338c-11ea-910d-99f53caecf83.png)

**Comment by StevenAWhite** [comment]
Lets take a step back.   Since you built BioGears your build folder should have a directory named `runtime` inside it.  This directory is created by the target _stage_runtime_  and should be automatically recreated by all other targets if it is deleted.

Assuming your build directory is simply named build and in `~/Desktop/biogears/core/buid` then to test run all the binaries you have built you should do the following

```cd ~/Desktop/biogears/core/build/runtime

**Comment by StevenAWhite** [comment]
So running BioGears from your build directory is perfectly fine if all you need to do is write Scenario.xml files and execute them.  However, if you plan on integrating with BioGears and wish to use the library there are a few considerations that need to be understood. 

 1. Biogears currently must have a valid _working_directory_ to execute from.
    a.  By default the location of the _working_directory_ is ${PWD} of the calling function
    b.  All of our example binaries have no way to change the default_location
    c.  An override for the _working_directory_ can be given at the API level when calling _CreateBioGearsEngine_
```
//-------------------------------------------------------------------------------
std::unique_ptr<biogears::PhysiologyEngine> CreateBioGearsEngine(const std::string working_dir, const std::string logfile)
{
  return std::make_unique<BioGearsEngine>(logfile, working_dir);
}
```
2. The contents of  a valid _working_directory_ is a copy of the xsd folder from share and all of the files in share/data/ . Manually creating one would look like the following
```
   mkdir ~/biogears_workdir
   cp  -R ~/Desktop/biogears/core/share/data/* ~/biogears_workdir/
   cp -R  ~/Desktop/biogears/core/share/xsd   ~/biogears_workdir/
```

So, when you install biogears using something like `ninja install`.  CMake will create a folder structure like the following

```
    CMAKE_INSTALL_PREFIX
   |`- bin
   |    |- cmd_bio
   |    `- scenario_builder
   |`- include
   |    `biogears/
   |`- share
   |    `-biogears/
   |       |-data/
   |       `-xsd/
   `- lib
       |- libbiogears.so
       |- libbiogears_cdm.so
       `-cmake\
          `-biogears\
```

You can construct your own runtime directories from copying the contents of share/biogears/{data/xsd} the same way you as the above example from copying it from the sourcetree, but the real reason this share structure is included is that the cmake files including in lib/cmake/biogears include macros for automatically staging runtime_dir in the build folder of any cmake project that uses `find_package(Biogears)`  Given our very large fileio requirement to bootstrap a run we haven't really worked on any cleaner system, but it is likely that future releases of BioGears after 7.3.0 will include support for ENV variables for the location of the XSD files and the Data files.  

I hope this helps you work through your runtime issue and explain why it has to be done.  I'll try to improve our documentation this week to explain all these requirements and integration in a more concise manor.

**Comment by ahamdy47** [comment]
Thank you mate! I was able to resolve my issues with your help!
