### ISSUE TITLE
Respiration response during pneumothorax

### ISSUE THREAD

**Issue by draum** [BioGearsEngine/core#15]
When a patient with a pneumothorax has a heart rate of 125, their respiration rate should be around 24 bpm.  While testing BG 7.3.0 the patient has a heart rate of 143, but only a respiration rate of 18 bpm which is considered clinically stable.  We've noticed this with other airway obstructions as well, the respiration rate just does not elevate as it should given the patient's heart rate.   This responded more appropriately in earlier versions of Biogears (prior to about October 2019?).

REF for proper pneumo HR/RR responses: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3982243/

**Comment by ajbaird** [comment]
Hey doug, 

Great comment, we currently have a feature branch out that fixes this issue. We should have that integrated for a upcoming 7.3.1 release that fixes a few other bugs. I'd say for now either revert to a 7.2 commit, or just run the pneumothorax at a 1.00 severity. Fix should be in in a week or two and I'll be sure to update this ticket when that happens.

**Comment by ajbaird** [comment]
We are almost done with a feature branch addressing this. Just letting you know it's on our radar.

**Comment by ajbaird** [comment]
Baroreceptor updates have been merged into master. Feel free to pull and test on your end.
