### ISSUE TITLE
Error while building core from source

### ISSUE THREAD

**Issue by meyash** [BioGearsEngine/core#17]
OS : ubuntu 18

After running : cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=/opt/biogears/usr -DCMAKE_PREFIX_PATH=/opt/biogears/external  -DBiogears_BUILD_JAVATOOLS=OFF -DBiogears_BUILD_HOWTOS=OFF ..

Error : 
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/yashwant/src/cmake-3.12.0-rc3/opt/biogears/core/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_6a792"
[1/2] Building C object CMakeFiles/cmTC_6a792.dir/CheckSymbolExists.c.o
[2/2] Linking C executable cmTC_6a792
FAILED: cmTC_6a792 
: && /usr/bin/cc    CMakeFiles/cmTC_6a792.dir/CheckSymbolExists.c.o  -o cmTC_6a792   && :
CMakeFiles/cmTC_6a792.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

File /home/yashwant/src/cmake-3.12.0-rc3/opt/biogears/core/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/yashwant/src/cmake-3.12.0-rc3/opt/biogears/core/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_58310"
[1/2] Building C object CMakeFiles/cmTC_58310.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_58310
FAILED: cmTC_58310 
: && /usr/bin/cc -DCHECK_FUNCTION_EXISTS=pthread_create   CMakeFiles/cmTC_58310.dir/CheckFunctionExists.c.o  -o cmTC_58310  -lpthreads && :
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Determining if the arc4random_buf exist failed with the following output:
Change Dir: /home/yashwant/src/cmake-3.12.0-rc3/opt/biogears/core/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_acef5"
[1/2] Building C object CMakeFiles/cmTC_acef5.dir/CheckSymbolExists.c.o
FAILED: CMakeFiles/cmTC_acef5.dir/CheckSymbolExists.c.o 
/usr/bin/cc    -o CMakeFiles/cmTC_acef5.dir/CheckSymbolExists.c.o   -c CheckSymbolExists.c
CheckSymbolExists.c: In function ‘main’:
CheckSymbolExists.c:8:19: error: ‘arc4random_buf’ undeclared (first use in this function); did you mean ‘srandom_r’?
   return ((int*)(&arc4random_buf))[argc];
                   ^~~~~~~~~~~~~~
                   srandom_r
CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.

File /home/yashwant/src/cmake-3.12.0-rc3/opt/biogears/core/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdlib.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef arc4random_buf
  return ((int*)(&arc4random_buf))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by StevenAWhite** [comment]
Verify your g++ installation for me. Follow the full instructions here

https://linuxconfig.org/how-to-install-g-the-c-compiler-on-ubuntu-18-04-bionic-beaver-linux

Then post the results of 
uname -a and g++ -v

**Comment by meyash** [comment]
![Screenshot from 2020-03-24 02-08-59](https://user-images.githubusercontent.com/21121279/77361211-ed1dab80-6d74-11ea-8677-3385b33142ec.png)
![Screenshot from 2020-03-24 02-11-35](https://user-images.githubusercontent.com/21121279/77361224-f149c900-6d74-11ea-84db-58e863d80b69.png)

**Comment by alekhgupta1441** [comment]
@meyash I think you should upgrade your cmake version to 3.15. It may resolve the issue as I had to do that when I built the "core".

**Comment by meyash** [comment]
My error was fixed after upgrading.
