### ISSUE TITLE
Refactor: C++11 API Modernization

### ISSUE THREAD

**Issue by StevenAWhite** [BioGearsEngine/core#24]
This issue is a place holder for future API breaking changes.  The BioGears team would like to bring the naming scheme of the API inline with post C++11 standards. Many of these choices can seem arbitrary so community involvement is encouraged. The following is an early list of bullet points which will be expanded on

## Suggested Changes
 * Rename CreatePhysiologyEngine to BioGearsFactory::make_unique and BioGearsFactor::make_shared
* Update const correctness in PhysiologyEngine and BIoGearsPhysiologyEngine
* Improve Doxygen comments of both classes. 
* Add Move constructors and assignment operators for most types
* Expose protected constructors to allow make_unique and make_shared calls.

**Comment by aniket-chowdhury** [comment]
> This issue is a place holder for future API breaking changes. The BioGears team would like to bring the naming scheme of the API inline with post C++11 standards. Many of these choices can seem arbitrary so community involvement is encouraged. The following is an early list of bullet points which will be expanded on
> 
> ## Suggested Changes

I would like to help with this part


> * Rename CreatePhysiologyEngine to BioGearsFactory::make_unique and BioGearsFactor::make_shared

And this one. 

> * Update const correctness in PhysiologyEngine and BIoGearsPhysiologyEngine

Might as well do this.

> * Improve Doxygen comments of both classes.

We can work on these later perhaps?

> * Add Move constructors and assignment operators for most types
> * Expose protected constructors to allow make_unique and make_shared calls.

Assign me if you would like me to work on these.

**Comment by StevenAWhite** [comment]
Close
