### ISSUE TITLE
Refactor: Remove or Replace Log4cpp

### ISSUE THREAD

**Issue by StevenAWhite** [BioGearsEngine/core#26]
I believe our variant of Log4j is no longer maintained actively.  I would suggest we use this time to reevaluate the need for such a large logging system and the possibility of Refactoring Logger.cpp to use a different logging implementation.  C++11/14.  

We do use a lot of features of Log4Cpp to allow multiple active streams, but I believe boost::logger and the other Log4j clones can replicate all of this behavior. If we limit our logging to simply 3 std::ostreams we could likely hand roll an equivalent functionality and remove a third party dep. 

## Goals
* Simplify building of BioGears.
* Ensure all dependencies maintained.

## Who benefits
* Any user who builds BioGears from source
* Developers on non standard platforms

## Candidates boost::log, log4cxx, log4cplus, std::ostream

**Comment by artorias111** [comment]
Hey! Can I take up this issue if it's still active? Would like to work on it

**Comment by StevenAWhite** [comment]
This is very open for development.  The patch is fairly straight forward all of the code that deals with log4cpp is located in Logger.cpp in our code base.  One just needs to refactor that file to use a different library.  

Most of the benefits that log4cpp brings to the project are negated by the fact that we do not do multi threaded logging.  Except in our bg-cli utility which I think could easily just be reworked using standard streams.

I would prefer we go in the direction of less third party deps then more.  I love boost and we already optionally link against it, but it is a large project that we might want to initially avoid.  I'm not sure how healthy the other log4j c++ ports are, but I honestly think this can all be done  using standard iostreams since we don't support socket based logging.  I would be interested in seeing a refactor that tries to accomplish the features of log4cpp we use with minimal outside libraries.  

I would expect this implementation would allow the following

Simultaneous Logging to File and Console
Log Filtering based on Severity
Time Stamped Logs
Log Level in log messages
Stretch Goal ability to run multiple logs with different log filters.

What I would expect to loose is the custom log message formatting that log4cpp allows. I assume we would either only have one message format or an enum of possible message formats that were pre determined. 

[ date in ISO 8601 ] [ Level ] : Message

Alternatively, if any of the log4j that are more actively maintained ports are easy to build and behave cleanly I am willing to accept integration with one of them as an alternative. If you have any more questions visit biogears.dev and join our slack channel.

**Comment by artorias111** [comment]
Sure thanks a lot! I'll get working on it

**Comment by mohit-cloud** [comment]
hey is someone working on this issue otherwise I would like to?

**Comment by artorias111** [comment]
Hey!, I was working on it, but I had a lot of things come up all of sudden so I'm unable to work on this at the moment. You can go ahead and work on it @mohit-cloud

**Comment by StevenAWhite** [comment]
There has been some discussion in SLACK about it, but the problem does require some attention and regression testing.  So, no one has taken it up for completion yet.
