### ISSUE TITLE
Bug: AdvanceModelTime Rounding Error

### ISSUE THREAD

**Issue by StevenAWhite** [BioGearsEngine/core#31]
Verify that Advance Model time does not truncate model time advances if the input is not a multiple of a given DeltaT.  If so retain the round off until it accumulates to a DeltaT and apply it in addition to the advancement.

**Comment by alekhgupta1441** [comment]
@StevenAWhite I was working on this issue. I tried to reproduce this issue. Whatever i get till now that for passing any parameter say 5, 6, 7... sec. to AdvanceModelTime in howto-engine time of simulation is always 5.02,6.02 or 7.02 sec. So, this needs to be corrected.

**Comment by StevenAWhite** [comment]
So our update rate is 50hz.   meaning the small increment is 0.02.  If you tell BioGears to advance fro 0.05 seconds it will swallow the 0.01.    I'll also test if the off by one deltaT error is cumulative or just on the first run.

**Comment by alekhgupta1441** [comment]
@StevenAWhite If I can do some further work for this or related to code changes which according to you are feasible for me can be communicated. I will love to contribute to this brilliant project.

**Comment by StevenAWhite** [comment]
-- Merged
