### ISSUE TITLE
Wiki update required and Feature Request:Automated Build

### ISSUE THREAD

**Issue by aniket-chowdhury** [BioGearsEngine/core#34]
Dependency broken for xeres-c-3.2.1

`Resolving mirror.olnevhost.net (mirror.olnevhost.net)... 188.165.227.148
Connecting to mirror.olnevhost.net (mirror.olnevhost.net)|188.165.227.148|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-30 04:18:32 ERROR 404: Not Found.`

Was able to successfully build core from `xerces-c-3.2.2.tar.gz` from a different mirror. Documentation needs update. 

Also, does BioGears have an automated build? It surely needs one or users might keep running into broken dependencies.

**Comment by StevenAWhite** [comment]
Its kind of the problem with putting a specific non self hosted mirror.  I'll verify and the mirror.  Our documentation is not part of our CI, just simply a guide to get people started.
