### ISSUE TITLE
Is there support for CBRNE

### ISSUE THREAD

**Issue by ahamdy47** [BioGearsEngine/core#35]
Is there a specific CBRNE interface or is there a set of chemicals that could be given to the physiology?
Would this be known chemicals that cause specific reactions?
Is there a list of known agents and associated medications?

**Comment by ajbaird** [comment]
Hi Ed, 

Yes BioGears has models for burn inflammation, sepsis, and organophosphate exposure. We support a reversal agent to Sarin exposure in the form of pralidoxime. More details on the model can be found here: https://www.biogearsengine.com/documentation/_drugs_methodology.html#sarin-nerve. Let me know if you need anymore assistance.

**Comment by ajbaird** [comment]
let me know if you have any additional questions, otherwise I will close this issue tomorrow.
