### ISSUE TITLE
Create nasal Naloxone demonstration using biogears UI

### ISSUE THREAD

**Issue by ajbaird** [BioGearsEngine/core#41]
- Download biogears user interface 
- Record instructions to create overdose scenarios 
- Upload video to our Youtube channel

**Comment by shubhamcodez** [comment]
Hey , can I do it? or is it assigned to somebody? also , what does the label say Summer of Code  ?

**Comment by ajbaird** [comment]
Hi! Happy to have you pick this issue up but it will need to wait until we get to wrapping up the 1.0 release of the UI. Check the UI code base to get started! 

Thanks! 

Austin

**Comment by shubhamcodez** [comment]
> Hi! Happy to have you pick this issue up but it will need to wait until we get to wrapping up the 1.0 release of the UI. Check the UI code base to get started!
> 
> Thanks!
> 
> Austin

Sure, No problem
