### ISSUE TITLE
Re-write CMD2MD.java class in python

### ISSUE THREAD

**Issue by ajbaird** [BioGearsEngine/core#44]
- Create a python class that matches the functionality in the java class 
- update cmake files to call the python file 
- demonstrate that the website gets generated and is equivalent to the java functionality

**Comment by Shashankjain12** [comment]
@ajbaird  @StevenAWhite  @LucasJMO I have replaced the Java Files with the files implemented in python for the process I have created

1. XSDToDoxygen.py - This file generates the schema of the whole defgroups and store all the schema in file xsd.ixx.This can be executed as:-
`python XSDToDoxgen.py -p <Path to xsd files> -f <xsd.ixx path>`
2. CDM2MD.py - This file generates all of the corresponding tables according to all of the specific Property names,Types and their corresponding definition. This can be executed as:-
`python CDM2MD.py`
3. DoxygenPreprocessor.py - This file generates all of the corresponding .md files under processed_md folder inside docs/doxygen by replacing all of the corresponding @insert <path> statements by the corresponding <path> files this file can be executed using
`python DoxygenPreprocessor.py -p <path to markdown or methodology> -f <path to processed_md>`

**Comment by Shashankjain12** [comment]
I have updated CMakeFiles as well to suppport Python as well and thereby added targets
1. docs-prepare-py - To prepare the documentation that is to create a processed_md directory and thereby placing all of the required executions of python files namely XSDToDoxygen.py, CDM2MD.py and DoxygenPreprocessor.py files are executing by running this target which is the first step to generate and populate the processed_md directory.
2. docs-doxygen-py - To execute the Doxygen file which is used to generate the documentation website which can be seen by executing all of the md files under processed_md directory.
3. docs-stage-py - To save the documentation in the form of zip file as well as output files which can be viewed using doc/output/documentation directory inside build.

And to execute those targets we need to first create a build directory then we need to run this command to generate targets
`cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=/opt/biogears/usr  -DBiogears_Python_BUILD_WEBSITE=ON  -DBiogears_BUILD_HOWTOS=OFF  -DBiogears_WEBSITE_TOOLS=ON  ..`

**Comment by StevenAWhite** [comment]
-- Pull Request Accepted and Ready for Merge
