### ISSUE TITLE
CDM Tables page error

### ISSUE THREAD

**Issue by riggs** [BioGearsEngine/core#5]
There is a display error for the [Environmental Conditions table](https://biogearsengine.com/documentation/_c_d_m_tables.html#EnvironmentalConditionsTable) on the CDM Tables page.

<img width="1316" alt="Screen Shot 2019-03-15 at 2 18 27 PM" src="https://user-images.githubusercontent.com/584232/54457046-587a7980-472e-11e9-9833-9b993e5b9cea.png">

**Comment by riggs** [comment]
Also happens with the [Mechanical Ventilation table](https://biogearsengine.com/documentation/_c_d_m_tables.html#MechanicalVentilationTable).

**Comment by StevenAWhite** [comment]
Hopefully, I will have time tomorrow to fix this issue.

**Comment by ajbaird** [comment]
I'm not able to recreate the mechanical ventilation table error. Also we are transitioning to a new website and should have new/revised documentation and new validation tables added. Might take some time to update this particular table but we will keep you posted and try and fix it as soon as we have time.

**Comment by riggs** [comment]
<img width="1169" alt="Screen Shot 2019-03-18 at 12 13 28 PM" src="https://user-images.githubusercontent.com/584232/54549127-68d16500-4977-11e9-9a36-7f78e7c6050a.png">
I get the same result on multiple browsers.

What's the timeline for the new site? We have documentation linking to the current site..

**Comment by StevenAWhite** [comment]
I've patched the rendering issue for now. I'll have to go through the rest of the generated sites sometime and look for the occurrence of pipes |.  So, our doxygen generation apparently has some flaws in it when types are missing information. I'll try to nail this down the next time we generate the website.
