### ISSUE TITLE
Broken Links for Build Dependencies

### ISSUE THREAD

**Issue by hienschi** [BioGearsEngine/core#52]
Hello! I was following the tutorial and I wasn't able to download the project xerces-c and eigen. It leads to this page below. Could you update the link of the page below. Thank you!

https://github.com/BioGearsEngine/core/wiki/Build-Instructions

**Comment by ajbaird** [comment]
I just updated the linking to the correct eigen version. There are a few more difficulties with xerces-c that might take a little longer.

**Comment by ajbaird** [comment]
@StevenAWhite will you review the binary releases of xerces-c and see how we want to move forward. Might need to test to see if older versions of xerces will work.

**Comment by ajbaird** [comment]
Hi all, looks like you need to use the newest version of xerces, I've updated the link to the build instructions. You'll need to download and build the newest version from source. I looked over the build instructions and they seem pretty straightforward.

**Comment by ajbaird** [comment]
Hi @hienschi , I'm going to consider this issue closed now that the links have been updates. Unfortuantely xercers is only supporting source code downloads so people building biogears will need to first build xerces. You can get around this on a linux/mac by using brew or apt-get package managers.

**Comment by hienschi** [comment]
Thanks for updating it quickly! If I run into anything, then I'll let you know.

**Comment by hienschi** [comment]
Thanks for updating it quickly! If I run into anything. I'll let you know.
- Hienschi
