### ISSUE TITLE
Bug: WSL2 builds are not producing log and CSV files.

### ISSUE THREAD

**Issue by avinal** [BioGearsEngine/core#53]
### Machine/platform
- distro: Ubuntu 20.04 focal(on the Windows Subsystem for Linux 2)
- Kernel : x86_64 Linux 4.19.128-microsoft-standard
### Steps to reproduce
- Build using steps on this page: https://github.com/BioGearsEngine/core/wiki/Compiling-on-Ubuntu-18.04-gcc-7-x86_64--using-Ubuntu-package-system 
- `cd build/runtime`
- `./../outputs/Release/bin/bg-cli VALIDATE drug` 
- Can run more tests and check `runtime/Scenario/Validation` for `.log` and `.csv` files.

### Expected Behaviour
Should produce both logs and CSV files after test runs
![image](https://user-images.githubusercontent.com/74113200/109698981-04386080-7bb6-11eb-9601-246e211ba7af.png)

### Observed Behaviour
not producing any output files

### What is working?
- console logs are working fine. 
- output files are being produced by similar distro builds (Ubuntu 20.04 not WSL2) and Windows builds

**Comment by StevenAWhite** [comment]
I'm about to push an IO over haul that I think will resolve this issue.  Should be ready by the end of may.

**Comment by StevenAWhite** [comment]
Master contains the IO overhaul for determining paths in and out. Might help with Log file completion in WSL2 I'm not sure. We have a pending graphical issue in one of our GUIs involving X11 forwarding which might give me opportunity to try and recreate this. Unfortunately I still can't
