### ISSUE TITLE
Looking to edit underlying circuit model for CV system

### ISSUE THREAD

**Issue by clobraico22** [BioGearsEngine/core#56]
I'm looking for some advice on how to modify the circuit for the CV system in BioGears (i.e. adding a resistor, capacitor, etc.). What would be the most straightforward way of doing this?

Would I be able to add elements to the underlying circuits by making my own howto? Or would I need to edit something deep within projects/biogears/libBiogears ?
Any assistance or advice would be greatly appreciated!

**Comment by ajbaird** [comment]
Hi @clobraico22 thanks for reaching out. Altering the underlying circuit can only be implemented by updating a few files in the core libraries. The two main places that circuits get constructed are BioGears.cpp and BioGearsCircuits.h. The best example would be the setupCerebral() routine which takes an existing ciruit on cardiovascular and implements a new (more detailed) brain circuit. I'd be happy to walk you through the process if you wanted. My email is abaird@ara.com

**Comment by clobraico22** [comment]
> Hi @clobraico22 thanks for reaching out. Altering the underlying circuit can only be implemented by updating a few files in the core libraries. The two main places that circuits get constructed are BioGears.cpp and BioGearsCircuits.h. The best example would be the setupCerebral() routine which takes an existing ciruit on cardiovascular and implements a new (more detailed) brain circuit. I'd be happy to walk you through the process if you wanted. My email is [abaird@ara.com](mailto:abaird@ara.com)

Hi Austin, appreciate the tips. I reached out to you via email, hoping you can provide me with more guidance. Thank you for your time!
