### ISSUE TITLE
Looking to control mean arterial pressure during simulation through drug infusion or patient action.

### ISSUE THREAD

**Issue by dfu5823** [BioGearsEngine/core#57]
I am seeking to control mean arterial pressure (MAP) during a how-to simulation scenario. 

I already have a how-to scenario set up that allows for drug infusion of Norepinephrine at user-specified time points. In addition to allowing Norepinephrine infusion, I also want to control mean arterial pressure during the simulation, preferably by a continuous infusion of another drug (preferably sodium nitroprusside, a potent drug that induces hypotension and a drop in MAP). However, sodium nitroprusside doesn't exist in the list of substances -- I am not looking for a perfect replica of the drug just a drug that will drop the blood pressure quickly (1 minute after administration) and will be cleared just as quickly when the infusion stops. 

I am wondering what steps I need to follow to create a new drug that will drop blood pressure. If the drug just acts primarily on the cardiovascular system then that's ok. I also don't care very much to model toxicity effects with cyanide. I know XML files in the core/share/data/substances folder are important - what other files if any should I modify to make sure that I can use this new drug in any scenario and how should I go about defining parameters for the drug?

Alternatively if making a drug is too difficult we could consider adding patient actions that will change the blood pressure during simulation, but I would prefer not to do that.

**Comment by ajbaird** [comment]
hi I was wondering if this issue resolved from our slack discussions, its fairly easy to develop new drugs in BioGears, its a matter of adding the proper .xml file with the desired EC50 values for blood pressure
