### ISSUE TITLE
bg-plotting tools instructions are out of date

### ISSUE THREAD

**Issue by ajbaird** [BioGearsEngine/core#59]
I noticed that the bg-plotting tool is not properly documented in the project. I feel like there might be documentation somewhere that is fairly good (with lots of examples) :) wondering if a wiki article could be added to document that workflow

**Comment by StevenAWhite** [comment]
I'm adding a wiki article with some basic examples of use

https://github.com/BioGearsEngine/core/wiki/Plotting-Tools

I need to find a landing spot for the images then close out the issue.

**Comment by ajbaird** [comment]
aweome you can close this out!
