### ISSUE TITLE
Missing 'pthreads.h' during a Windows 10 Visual Studio 15 x64 build

### ISSUE THREAD

**Issue by ghostravenstorm** [BioGearsEngine/core#6]
I'm walking through the install procedures and following along with the tutorial video.
https://www.youtube.com/watch?v=vWNUqZSDq3o

I keep getting stuck on the BioGears build where CMake can't find `pthreads.h`. 

```
cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_be8f5.dir\Debug\\" /Fd"cmTC_be8f5.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "C:\src\core-master\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  CheckIncludeFile.c

C:\src\core-master\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\src\core-master\build\CMakeFiles\CMakeTmp\cmTC_be8f5.vcxproj]
```

I downloaded `pthread.h`, `sched.h`, `semaphore.h`, and `pthreadVC2.lib` from https://sourceware.org/pthreads-win32/ . I placed the headers in `biogears/external/include` and the lib in `biogears/external/lib`. CMake still can't find `pthread`.

I even tried this: https://stackoverflow.com/questions/28975700/how-to-add-pthread-library-to-c-project-in-visual-studio-community-edition to get pthread in the visual studio environment.
Still same problem.

EDIT:
Okay, now the error I'm getting is in regard to `time.h` `timespec`.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\pthread.h(320): error C2011: 'timespec': 'struct' type redefinition [C:\src\core-master\build\CMakeFiles\CMakeTmp\cmTC_20004.vcxproj]

  C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\time.h(39): note: see declaration of 'timespec'
```

**Comment by StevenAWhite** [comment]
Have you tried building with the wiki instructions.

https://github.com/BioGearsEngine/core/wiki/Visual-Studio-2017-Win64

**Comment by ghostravenstorm** [comment]
> Have you tried building with the wiki instructions.
> 
> https://github.com/BioGearsEngine/core/wiki/Visual-Studio-2017-Win64
> 
> I want to make sure you get the same errors when you follow these build instructions.

Yes. I followed the build instructions and the tutorial video.
On a clean install of Windows 10, I installed CMake 3.14 and VS 15 2017 with C++ compilers and CLI tools. I built eigin, log4cpp, xerce-c-3.2.2 (because the download link for 3.2.1 is broken), dirent, and I copied the bin and lib from xsd to biogears/external.

That's my vanilla attempt following the instructions verbatim. Now I'm trying to include pthreads in there somehow since I can't get it building any other way.

Above is what the CMakeError.log has.
This is what the console outputs when prompting to check the logs.
```
CMake Warning at cmake/cmake-common_logic.cmake:46 (message):
  The following packages CodeSynthesis were not found.For native compilations
  setting CMAKE_PREFIX_PATH can solve this problemFor cross complilation try
  expanding your CMAKE_FIND_ROOT_PATH
Call Stack (most recent call first):
  projects/biogears/CMakeLists.txt:34 (verify_package)


CMake Error at cmake/cmake-common_logic.cmake:51 (message):
  Unable to find CodeSynthesis which is marked REQUIRED
Call Stack (most recent call first):
  projects/biogears/CMakeLists.txt:34 (verify_package)


-- Configuring incomplete, errors occurred!
See also "C:/src/core-master/build/CMakeFiles/CMakeOutput.log".
See also "C:/src/core-master/build/CMakeFiles/CMakeError.log".
```

**Comment by ajbaird** [comment]
Ok, so Steven can jump in here but it looks like you need to set the CMAKE_PREFIX_PATH = wherever your verification folder is. It needs to be able to link to our external dependencies to build.

**Comment by ghostravenstorm** [comment]
> Ok, so Steven can jump in here but it looks like you need to set the CMAKE_PREFIX_PATH = wherever your external folder is. It needs to be able to link to our external dependencies to build.

Is it PREFIX_PATH or INSTALL_PREFIX.
INSTALL_PREFIX in the build intruction has C:/biogears as the param.

**Comment by StevenAWhite** [comment]
OK, so our first goal is to remove all occurrences of this message from your configure log.  

>   The following packages CodeSynthesis were not found.For native compilations
  setting CMAKE_PREFIX_PATH can solve this problemFor cross complilation try
  expanding your CMAKE_FIND_ROOT_PATH

Your CMake environment is just invalid if your getting this message and everything that happens after that is what I would call undefined behavior.  Now, I've designed our instructions to assume all your external libraries are installed in a UNIX like layout in a single folder. It is a more advanced step but you can configure them to be installed in a WINDOW layout where each one has its own separate install tree, but I think this overly complicates the issue of finding your Dependencies.

By Default CMake searchs a number of standard directories for each package I'm searching for in this case. 

| Project | Version  | Release Date  | URL  |
|---|---|---|---|
|  eigen | 3.3.4  |  2017-12-29 | [zip](http://bitbucket.org/eigen/eigen/get/3.3.4.zip) [tar.gz](http://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz)  |
|  log4cpp | 1.1.4  |  2018-07-12 | [zip](https://github.com/StevenAWhite/log4cpp/archive/master.zip)  |
|  xerces-c |   3.2.1 | 2010-04-21 | [zip](http://mirror.olnevhost.net/pub/apache//xerces/c/3/sources/xerces-c-3.2.1.zip) [tar.gz](http://mirror.olnevhost.net/pub/apache//xerces/c/3/sources/xerces-c-3.2.1.tar.gz)  |
|  xsd | 4.0  |  2014-07-22 | [zip](https://www.codesynthesis.com/download/xsd/4.0/windows/i686/xsd-4.0.0-i686-windows.zip) [tar.gz](https://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd-4.0.0-x86_64-linux-gnu.tar.bz2)  |
|dirent.h  | [toronkko/dirent](https://github.com/tronkko/dirent/) | | [zip](https://github.com/StevenAWhite/dirent/archive/master.zip)

For each of these packages CMake in general searches for a specific include file and a specific library file to determine if it is present. It searches among the prelisted directories and any directory you list in CMAKE_PREFIX_PATH. For the header files it appeands include/ to each path and for libs it appends lib/.  Once they are found each dep has its own assumptions to make and will fill out the required variables.

That being said this process is just way easier if you just have one folder biogears-external that has the following layout

biogears-external/
  bin/
  include/
  lib/

  For XSD the following files are searched for
    xsd/cxx/version.hxx
    xsd.exe (This file should be relative to the folder containing the xsd/cxx/version.hxx by  ../bin )
    XSD also requires CMake to find Xerces-C which has a slightly more complicated library search because it accepts multiple names for the same library.
    
  For Xerces-C the following files are search for
    xercesc/dom/DOM.hpp
    One of the following librarys
    	xerces-c_static_3
        libxerces-c_static_3
        xerces-c_static_3_2
        libxerces-c_static_3_2
        xerces-c
        libxerces-c
    Or one of the following libraries
        xerces-c_3
        libxerces-c_3
        xerces-c_3_2
        libxerces-c_3_2
        xerces-c
        libxerces-c

I would start by verifying you have all of the deps extracted in a single location in the layout listed above. Then verifying the value of CMAKE_PREFIX_PATH is set to the folderpath where your externals are.  If your using the CMake GUI then CMAKE_PREFIX_PATH is not a default variable, so you need to use the add variable button on the upper left.  The Variable Type is STRING or PATH and simply paste in or auto complete the directory you completed. Then run configure again and see if it finds XSD Code Synthesis. If it doesn't verify the presence of all the files in the directory you set CMAKE_PREFIX_PATH path to and send us the complete CMakeCache.txt to review.

**Comment by ajbaird** [comment]
![Capture](https://user-images.githubusercontent.com/903215/58185198-8f19c680-7c80-11e9-9ed9-826f23c69d22.PNG)

**Comment by ajbaird** [comment]
this is the example for my particular external directory

**Comment by StevenAWhite** [comment]
![Capture](https://user-images.githubusercontent.com/39066734/58185308-d43df880-7c80-11e9-8c00-deb6ac035ef4.PNG)

**Comment by ghostravenstorm** [comment]
I tried rebuilding everything in a fresh VM of WIndows 10, and I'm able to get a successful build. I tried it again on my base machine, and it's building correctly now. Not sure what caused the initial build errors, but once I cleared everything and started fresh with new downloads and all, it's working now.

**Comment by ajbaird** [comment]
Glad you got up and running! if you'd like more assistance let me know. If you have more detailed modeling/sim questions always feel free to shoot me an email: abaird@ara.com
