### ISSUE TITLE
Compiling on Visual Studio 2019 Win 64 is out of date

### ISSUE THREAD

**Issue by askmydog** [BioGearsEngine/core#63]
Hi,

This is in regard to the wikis: 
https://github.com/BioGearsEngine/core/wiki/Compiling-on--Visual-Studio-2019-Win64
https://github.com/BioGearsEngine/core/wiki/Build-Instructions

There are several issues with the build instructions:
1) There is a new version of Visual Studio, so the cmake code excerpts are incorrect 
  They currently say: `cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:/biogears/external`
  They need to say `cmake .. -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=C:/biogears/external`

2) Several of the build dependency links are old
  The link to "Build Instructions" for xerxes-c links to a page with basically no helpful information, and does not link to the correct dependency.
  It probably needs to point to https://www.codesynthesis.com/products/xsd/download.xhtml
  The link to dirent-master doesn't seem to be the most up to date version (should be https://github.com/tronkko/dirent/releases)

3) Less of an issue, more of a suggestion: The instructions make very littles sense for people without C++ experience, so when things go wrong it's very hard to troubleshoot.  It might help to include a troubleshooting section if possible.

**Comment by StevenAWhite** [comment]
1. The instructions you are quoting are for building with 2019 and 2017 not 2022. So, no update is needed. BioGears does compile with 2022, but for many reasons the core team does not currently release 2022 Binaries and so no update is needed.

2.  I trust that anyone with enough experience to read these instructions can use google if the links go stale. For me all the links are valid today so I see no reason to update at this time.  

3.   I would not call the instructions as written complex.   It is expected that people building a project like BioGears have some development experience as it will be very hard to do anything with BioGears a lot of familiarity with C++ development.  For our end users of language hooks I would expect our next release to include all the link libraries needed to develop with out building it, but right now as they are heavily experimental you still need to understand C++ to debug the hooks.
