### ISSUE TITLE
Unable to compile BioGears due to "Unable to find CodeSynthesis which is marked REQUIRED" error

### ISSUE THREAD

**Issue by askmydog** [BioGearsEngine/core#64]
I've followed the compile instructions at https://github.com/BioGearsEngine/core/wiki/Compiling-on--Visual-Studio-2019-Win64, including the following: 

> XSD is shipped as a binary solution. To simplify the install
> 
> copy xsd-4.0.0-i686-windows/bin to C:/biogears/external
> copy xsd-4.0.0-i686-windows/libxsd/xsd C:/biogears/external/include

Here's my `C:/biogears/external` directory:
```
PS C:\biogears\external> dir

    Directory: C:\biogears\external

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           4/12/2022  1:32 PM                bin
d----           4/12/2022  1:24 PM                cmake
d----           4/12/2022  1:33 PM                include
d----           4/12/2022  1:23 PM                lib
d----           4/12/2022  1:23 PM                share
```
```
PS C:\biogears\external\include> dir

    Directory: C:\biogears\external\include

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           4/12/2022 12:57 PM                eigen3
d----           4/12/2022  1:05 PM                log4cpp
d----           4/12/2022  1:23 PM                xercesc
d----           4/12/2022  1:33 PM                xsd
-a---           4/12/2022  1:28 PM          27456 dirent.h
```

When I try to compile Biogears, I get this error.

```PS C:\biogears\core\build> cmake -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=C:/biogears/usr -DCMAKE_PREFIX_PATH=C:/biogears/external -DBiogears_BUILD_HOWTOS=ON ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The CXX compiler identification is MSVC 19.31.31104.0
-- The C compiler identification is MSVC 19.31.31104.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- 
    Using the following search paths
    CMAKE_MODULE_PATH = C:/biogears/core/cmake;C:/biogears/core/cmake;C:/biogears/core/cmake/common   
    CMAKE_PREFIX_PATH  = C:/biogears/external
    CMAKE_FIND_ROOT_PATH =

-- GIT_REV=7.5.0-60-gccc3ca06
-- VS_DEBUGGER_ENVIRONMENT_LIST=PATH=C:/biogears/external/bin;C:/biogears/external/lib;%PATH%
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Configuring biogears_common
CMake Warning at cmake/cmake-common_logic.cmake:43 (message):
  The following packages CodeSynthesis were not found.For native compilations
  setting CMAKE_PREFIX_PATH can solve this problemFor cross complilation try
  expanding your CMAKE_FIND_ROOT_PATH
Call Stack (most recent call first):
  projects/biogears/CMakeLists.txt:38 (verify_package)


CMake Error at cmake/cmake-common_logic.cmake:48 (message):
  Unable to find CodeSynthesis which is marked REQUIRED
Call Stack (most recent call first):
  projects/biogears/CMakeLists.txt:38 (verify_package)


-- Configuring incomplete, errors occurred!
See also "C:/biogears/core/build/CMakeFiles/CMakeOutput.log".
See also "C:/biogears/core/build/CMakeFiles/CMakeError.log".
```

I've attached my CMakeError.log and CMakeOutput.log files.  
[CMakeOutput.log](https://github.com/BioGearsEngine/core/files/8483473/CMakeOutput.log)
[CMakeError.log](https://github.com/BioGearsEngine/core/files/8483478/CMakeError.log)

Can anyone help with this?

**Comment by StevenAWhite** [comment]
This boils down to this.  You must set your CMAKE_PREFIX_PATH to include the directy above bin/xsd.exe and include/xsd. They can be along separate paths or combined under a single tree, but CMake is simply finding and validating XSD is installed by the presences of bin/xsd.exe and include/xsd/cxx/version.hxx if these exist and Xerces-c_FOUND is true the XSD_FOUDN is set to true.

**Comment by StevenAWhite** [comment]
You can review the CMAKE search behavior  https://cmake.org/cmake/help/latest/command/find_file.html

I can help further but you will need to post the full path to xsd.exe and version.hxx to verify they are in the correct place along with xercesc/dom/DOM.hpp and your xercesc lib and dll.  A lot can go wrong with that as the xerces-c dlls have several names and we have to kind of brute force search all the common name variants

You can read all of logic used to find these packages in the following location <biogears_root>/cmake/common

**Comment by StevenAWhite** [comment]
As a note if you need real time help compiling any of this you should join us on slack

https://www.biogears.dev/

Just leave a post in support and we will try to walk you through it.

**Comment by askmydog** [comment]
Thank you and joined! I haven't had a chance to implement this, I'll post results in the next day or two.

**Comment by StevenAWhite** [comment]
No problem.  @askmydog  I did update the instructions to include Visual Studio 2022

**Comment by askmydog** [comment]
I just happened to look to try the build process again, and I saw that you
had.  Thank you!

**Comment by StevenAWhite** [comment]
Closing
