### ISSUE TITLE
Wiki Has Incorrect cmake arguments for building core

### ISSUE THREAD

**Issue by mariolopjr** [BioGearsEngine/core#7]
If you go to the following build instructions for all platforms, you see the following build instructions for building the biogears core:

```shell
cd ~/Desktop/biogears
git clone https://github.com/BioGearsEngine/core.git core
cd core
mkdir build; cd build
cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=/opt/biogears/usr \
                 -DCMAKE_PREFIX_PREFIX_PATH='/usr/local/opt;/User/abaird/biogearsExternal/xsd-4.0.0-i686-macosx'
                 -DARA_Biogears_BUILD_JAVATOOLS=OFF \ 
                 -DARA_Biogears_BUILD_HOWTOS=OFF \
                 ..

ninja scenario_driver
```

The issue is, the BUILD_JAVATOOLS and BUILD_HOWTOS changed to not have ARA_ prepended to the argument. This causes issues when building the core under the expectation that JAVA is not utilized.

I am unable to update the wiki, but it looks like every example for building the core needs to be updated.

Please let me know if you have any questions, thanks! -m

**Comment by StevenAWhite** [comment]
Thanks, for the issue.  I pulled the ARA_ branding from our CMAKE and missed the documentation references.  I believe I fixed all the references in the github wiki this morning, but I still need to comb over any README.MD files in the main repo.
