### ISSUE TITLE
Can't build BioGears docker container using existing codebase

### ISSUE THREAD

**Issue by cjus** [BioGearsEngine/core#8]
I have a goal of building a BioGears container which includes some other software I'm building. This prevents me from using the stock BioGears container which is also about a year old.

So I tried using the Dockerfiles referenced on the Docker Hub page for BioGears.

The [release Dockerfile]( https://github.com/BioGearsEngine/core/tree/master/docker/release) referenced depends on `biogears-external`. However, biogears-external does not appear on https://hub.docker.com/u/biogears . Attempting to pull that image results in unauthorized access.

Additionally, the second line in the above Dockerfile proceeds to issue `RUN git clone https://github.com/BioGearsEngine/core.git && mkdir core/build` which is potentially problematic as it pulls the latest version of the code posted on Github which may not be stable.

So I tried to build a new Dockerfile which essentially combines what the [biogears-external](https://github.com/BioGearsEngine/core/tree/master/docker/external) Docker file does with what the [release docker file](https://github.com/BioGearsEngine/core/blob/master/docker/release/Dockerfile#L1) proceeds to do:

```
FROM ubuntu:18.04
RUN apt update && apt -y install git wget ninja-build libncurses5-dev build-essential g++ automake libeigen3-dev liblog4cpp5-dev libxerces-c-dev

WORKDIR /root/src
RUN wget https://cmake.org/files/v3.12/cmake-3.12.0-rc3.tar.gz && tar -xf cmake-3.12.0-rc3.tar.gz && wget https://www.codesynthesis.com/download/xsd/4.0/linux-gnu/x86_64/xsd_4.0.0-1_amd64.deb && dpkg -i xsd_4.0.0-1_amd64.deb
WORKDIR /root/src/cmake-3.12.0-rc3
RUN ./bootstrap --parallel=4 --prefix=/usr/local && make -j4 && make install
WORKDIR /opt/biogears

RUN git clone https://github.com/BioGearsEngine/core.git && mkdir core/build
WORKDIR core/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/opt/biogears/usr -DARA_Biogears_BUILD_JAVATOOLS=OFF -DARA_Biogears_BUILD_HOWTOS=ON -DCMAKE_BUILD_TYPE=Release .. && make -j4
WORKDIR runtime
```

This results in a compiler error. I'm investigating whether it was an out of memory issue. In the meantime could someone confirm whether the above docker file should work given the current code base in master?

**Comment by cjus** [comment]
I'm using the Docker Desktop on Mac. Docker engine version: 18.09.2 . By default I had 2GB of memory allocated to the local docker engine. Increasing the memory limit to 8 GB has solved the build problem.  The Docker file I posted above successfully builds BioGears.  The only change I'd make to my Docker file is perhaps changing this line : `RUN git clone https://github.com/BioGearsEngine/core.git && mkdir core/build` to pull a known release rather than latest.  That would ensure that a docker image would correspond with a known BioGears release.

**Comment by LucasJMO** [comment]
Thanks for your comment, and sorry for the delayed response. [We recommend having at least 5GB of disk space allocated to building BioGears](https://www.biogearsengine.com/download#d-source), that was likely what caused your previous issue.

**Comment by cjus** [comment]
@LucasJMO No worries - thanks for such an awesome project! I'm excited to continue my journey with BioGears. Please feel free to close this ticket.
