### ISSUE TITLE
SDK on 7.2.1

### ISSUE THREAD

**Issue by jeldalam** [BioGearsEngine/core#9]
Hi, can someone please post a release of SDK on latest (7.2.1) source code (Linux x64 and MacOS), or guide me how to grab the SDK stuff from the core build, there's no document on wiki show how to do that. I was using SDK 6.3.0 from the website and already built a program base on that. Now I want to upgrade it to 7.2.1.

With the latest source code, I can manage to build the core already but the structure and the dependencies is now different and there's no deploy_to.. file like old one anymore. So I'm stuck with the SDK step now.

**Comment by jeldalam** [comment]
Hi ajbaird,

I dowloaded the biogears-linux-x86_64-7.2.1.tar.gz already. But can you walk me through the build command, let say I copied the howto-exercise from source and customize it, place it in the SDK folder. Can you show me the command to build it.

Thanks

**Comment by jeldalam** [comment]
Ok, now I understand more on the new build system. I was able to build a custom howto base on your guide. Now if I want to move my source code to a separate project folder just like circuit_profiler, cmd_bio... and build it with a dedicate name instead of auto generated name: howto-xxx. Can you spare sometime make a simple CMakeLists.txt file so I can know which is need to include to build a small biogear program.

Thanks a lot for your help.

**Comment by StevenAWhite** [comment]
jeldalam

I'm currently creating wiki articles to assist you in setting up BioGears subprojects.  You may also be interested in just maintain your own build system and depending on BioGears as you would any other dep.  I'll include instructions for both in the new articles.

https://github.com/BioGearsEngine/core/wiki/Using-BioGears

**Comment by StevenAWhite** [comment]
Ok, the new examples are up on the Wiki.  I'll try to clarify any issues you come up with.  A hello world of cmake is only roughly three lines, but I added a little extra detail to show how to copy over DLLs you link against to your runtime directory so you can run it within visual studios.
